print("Введите 3 названия овоща:\n")
first = input()
second = input()
third = input()
print(first.lower(), second.lower(), third.lower())
print(first.upper(), second.upper(), third.upper())
print(first.capitalize(), second.capitalize(), third.capitalize())
print("Введите количество для ", first, " ")
amountF = int(input())
print("Введите количество для ", second, " ")
amountS = int(input())
print("Введите количество для ", third, " ")
amountT = int(input())
print("      Овощ| {:^10}| {:^10}| {:^10}\nКоличество| {:^10}| {:^10}| {:^10}".format(first, second, third, amountF, amountS, amountT))